config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'products#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    get :privacy_policy,            to: 'sample#privacy_policy'
    get 'categories/grid', to: 'categories#grid'
    get 'categories/list', to: 'categories#list'
    resources :products, only: [:show, :index]
    resources :categories, only: [:show, :index]
    resources :orders, only: [:index, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  include CommonActions
  before_action :current_order_and_line_items # app/controllers/concerns/common_action.rb:8
  SORT_VALUES =
    [
      ["新着順", "NEW_ARRIVAL"],
      ["価格の安い順", "LOW_PRICE"],
      ["価格の高い順", "HIGH_PRICE"],
      ["古い順", "OLD_ARRIVAL"],
    ].freeze
  MAX_NUMBER_OF_SEARCH_WORD_FOR_DISPLAY = 30
  DEFAULT_SEARCH_WORD_FOR_DISPLAY = 'Products searched'.freeze

  def index
    @taxonomies = Spree::Taxonomy.includes(taxons: [{ children: :products }, :products])
    @colors = Spree::OptionType.colors
    @sizes = Spree::OptionType.sizes
    @sort_values = SORT_VALUES
    @selected_sort_value = filter_params[:sort_order] || SORT_VALUES[0][1]
    if params[:search_word] && params[:search_word].size <= MAX_NUMBER_OF_SEARCH_WORD_FOR_DISPLAY
      @search_word = params[:search_word]
    elsif params[:search_word]
      @search_word = params[:search_word]
      @default_search_word = DEFAULT_SEARCH_WORD_FOR_DISPLAY
    end
    if @search_word.present?
      products_searched = Spree::Product.like_any([:name, :description], [params[:search_word]])
      products =
        products_searched.filter(taxon: nil, sort_order: filter_params[:sort_order], color_name: filter_params[:color_name], size_name: filter_params[:size_name], sort_value: @sort_values[0][1])
      @ids_of_products_in_current_taxon = products_searched.pluck(:id)
    else
      products =
        Spree::Product.filter(taxon: nil, sort_order: filter_params[:sort_order], color_name: filter_params[:color_name], size_name: filter_params[:size_name], sort_value: @sort_values[0][1])
      @ids_of_products_in_current_taxon = Spree::Product.pluck(:id)
    end
    @products =
      if products.class == Array
        Kaminari.paginate_array(products).page(filter_params[:page])
      else
        products.page(filter_params[:page])
      end
    render action: :show
  end

  def show
    @taxonomies = Spree::Taxonomy.includes(taxons: [{ children: :products }, :products])
    @taxon = Spree::Taxon.find(params[:id])
    @colors = Spree::OptionType.colors
    @sizes = Spree::OptionType.sizes
    @sort_values = SORT_VALUES
    @selected_sort_value = filter_params[:sort_order] || SORT_VALUES[0][1]
    products = Spree::Product.filter(taxon: @taxon, sort_order: filter_params[:sort_order], color_name: filter_params[:color_name], size_name: filter_params[:size_name], sort_value: @sort_values[0][1])
    @products =
      if products.class == Array
        Kaminari.paginate_array(products).page(filter_params[:page])
      else
        products.page(filter_params[:page])
      end
    @ids_of_products_in_current_taxon = @taxon.products.pluck(:id)
  end

  def grid
    session.delete(:display_style) if session[:display_style].present?
  end

  def list
    session[:display_style] = 'list'
  end

  private

  def filter_params
    { sort_order: params[:sort_order], color_name: params[:color_name], size_name: params[:size_name], page: params[:page] }
  end

  def resource_not_found
    message = "お探しの商品は見つかりませんでした。"
    flash[:danger] = message
    redirect_to controller: 'products', action: 'index'
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store
  CONSUMPTION_TAX_RATE = 0.08
  SHIPPING_COST_PER_1 = 200
  SHIPPING_COST = 650

  def index
    @order = current_order || Spree::Order.incomplete.find_or_initialize_by(guest_token: cookies.signed[:guest_token])
    @line_items = @order.line_items.includes(variant: [{ product: :variant_images }, :images])
    @item_or_items = @order.item_or_items
    @consumption_tax_total = @order.consumption_tax_total(consumption_tax_rate: CONSUMPTION_TAX_RATE)
    @shipment_cost_total = @order.shipment_cost_total(shipping_cost_per_1: SHIPPING_COST_PER_1, shipping_cost: SHIPPING_COST)
    @order_price_total = @order.order_price_total(consumption_tax_total: @consumption_tax_total, shipment_cost_total: @shipment_cost_total)
  end

  def create
    @order = Spree::Order.find_by(guest_token: cookies.signed[:guest_token]) || Spree::Order.create(guest_token: cookies.signed[:guest_token])

    variant  = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].to_i

    if !quantity.between?(1, 2_147_483_647)
      @order.errors.add(:base, t('spree.please_enter_reasonable_quantity'))
    end

    begin
      @line_item = Spree::Order.includes(line_items: :adjustments).find(@order.id).contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => e
      @order.errors.add(:base, e.record.errors.full_messages.join(", "))
    end

    if @order.errors.any?
      flash[:danger] = @order.errors.full_messages.join(", ")
      redirect_back_or_default potepan_path
      return
    else
      redirect_to potepan_orders_path
    end
  end

  def update
    @order = Spree::Order.includes([{ variants: :product }, { line_items: [:tax_category, :adjustments] }]).find_by(number: params[:number])
    @line_item_id = order_params[:line_items_attributes][0][:id]
    @line_item = @order.line_items.find(@line_item_id)
    @line_item_quantity_updated = @line_item.quantity_updated(calculation: params[:calculation])
    @order.contents.update_cart({ line_items_attributes: [{ id: @line_item_id, quantity: @line_item_quantity_updated }] })
    @item_or_items = @order.item_or_items
    @consumption_tax_total = @order.consumption_tax_total(consumption_tax_rate: CONSUMPTION_TAX_RATE)
    @shipment_cost_total = @order.shipment_cost_total(shipping_cost_per_1: SHIPPING_COST_PER_1, shipping_cost: SHIPPING_COST)
    @order_price_total = @order.order_price_total(consumption_tax_total: @consumption_tax_total, shipment_cost_total: @shipment_cost_total)
  end

  def destroy
    @line_item = Spree::LineItem.find(params[:id])
    @order = Spree::Order.includes([line_items: :adjustments]).find(@line_item.order_id)
    @order.contents.remove_line_item(@line_item)
    @item_or_items = @order.item_or_items
    @consumption_tax_total = @order.consumption_tax_total(consumption_tax_rate: CONSUMPTION_TAX_RATE)
    @shipment_cost_total = @order.shipment_cost_total(shipping_cost_per_1: SHIPPING_COST_PER_1, shipping_cost: SHIPPING_COST)
    @order_price_total = @order.order_price_total(consumption_tax_total: @consumption_tax_total, shipment_cost_total: @shipment_cost_total)
  end

  private

  def order_params
    params.require(:order).permit(line_items_attributes: [:id])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  include CommonActions
  before_action :current_order_and_line_items # app/controllers/concerns/common_action.rb:8
  NUMBER_OF_POPULAR_CATEGORIES = 3
  NUMBER_OF_NEW_PRODUCTS = 8
  MAX_NUMBER_OF_RELATED_PRODUCTS = 4
  REGEXP_OF_POTEPAN_CATEGORY_PATH = /potepan\/categories\/\d+/

  def index
    @popular_categories = Spree::Taxon.random_categories(NUMBER_OF_POPULAR_CATEGORIES)
    @display_products_in_popular_categories = @popular_categories.map { |taxon| taxon.products.first }
    @new_products = Spree::Product.new_products(number: NUMBER_OF_NEW_PRODUCTS)
  end

  def show
    @product = Spree::Product.find(params[:id])
    @images = @product.variant_images
    @related_products = @product.related_products(max_number: MAX_NUMBER_OF_RELATED_PRODUCTS)
    @taxon_id_and_name =
      @product.referrer_taxon_id_and_name(regexp_of_potepan_category_path: REGEXP_OF_POTEPAN_CATEGORY_PATH, request_referrer: request.referrer)
    arrange_referrer
  end

  private

  def arrange_referrer
    if request.referer&.match(REGEXP_OF_POTEPAN_CATEGORY_PATH)
      @referrer = request.referrer
    else
      @referrer = potepan_category_path(@product.taxons.ids.first)
    end
  end

  def resource_not_found
    message = "お探しの商品は見つかりませんでした。"
    flash[:danger] = message
    redirect_to controller: 'products', action: 'index'
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/views/potepan/categories/_display_buttons.html.slim
.col-xs-6.displayStyle
  - if session[:display_style] == 'list'
    .btn-group.pull-right[role="group"]
      = button_to potepan_categories_grid_path, method: :get, remote: true, class: 'btn btn-default', id: 'btnGrid', type: 'button' do
        i.fa.fa-th[aria-hidden="true"]
        span
          | Grid
      = button_to potepan_categories_list_path, method: :get, remote: true, class: 'btn btn-default active', id: 'btnList', type: 'button' do
        i.fa.fa-th[aria-hidden="true"]
        span
         | List
  - else
    .btn-group.pull-right[role="group"]
      = button_to potepan_categories_grid_path, method: :get, remote: true, class: 'btn btn-default active', id: 'btnGrid', type: 'button' do
        i.fa.fa-th[aria-hidden="true"]
        span
          | Grid
      = button_to potepan_categories_list_path, method: :get, remote: true, class: 'btn btn-default', id: 'btnList', type: 'button' do
        i.fa.fa-th[aria-hidden="true"]
        span
          | List

app/views/potepan/categories/_product.html.slim
- if session[:display_style] == 'list'
  .col-xs-12
    .media
      .media-left
        = image_tag product.display_image.attachment.url(:large), alt: "Image"
        span.maskingImage
          a.btn.viewBtn[data-toggle="modal" href="#{potepan_product_path(product.id)}"]
            | Quick View
      .media-body
        h4.media-heading
          a[href="#{potepan_product_path(product.id)}"]
            = product.name
        p
          = product.description
        h3
          = product.display_price
- else
  .col-sm-4.col-xs-12
    .productBox
      = link_to potepan_product_path(product.id) do
        .productImage.clearfix
          = image_tag product.display_image.attachment.url(:product), alt: "product_image"
        .productCaption.clearfix
          h5
            = product.name
          h3
            = product.display_price

app/views/potepan/categories/grid.js.slim
| window.location.reload();

app/views/potepan/categories/list.js.slim
| window.location.reload();

app/views/potepan/categories/show.html.slim
- if @taxon.present?
  - provide(:title, @taxon.name)
  = render 'layouts/light_section', taxon: @taxon, product: nil, sort_order: @selected_sort_value, default_search_word: nil, search_word: nil
- elsif @default_search_word.present?
  - provide(:title, @default_search_word)
  = render 'layouts/light_section', taxon: nil, product: nil, sort_order: @selected_sort_value, default_search_word: @default_search_word, search_word: @search_word
- elsif @search_word.present?
  - provide(:title, @search_word)
  = render 'layouts/light_section', taxon: nil, product: nil, sort_order: @selected_sort_value, default_search_word: nil, search_word: @search_word
- else
  - provide(:title, 'SHOP')
  = render 'layouts/light_section', taxon: nil, product: nil, sort_order: @selected_sort_value, default_search_word: nil, search_word: nil
.section.mainContent.clearfix.productsContent
  .container
    .row
      .col-md-3.col-sm-4.col-xs-12.sideBar
        .panel.panel-default
          .panel-heading
            | 商品カテゴリー
          .panel-body
            .collapse.navbar-collapse.navbar-ex1-collapse.navbar-side-collapse
              ul.nav.navbar-nav.side-nav
                - @taxonomies.each do |taxonomy|
                  li
                    = link_to "javascript:;", data: {toggle: "collapse", target: "##{taxonomy.id}"} do
                      = taxonomy.name
                      i.fa.fa-plus
                    ul.collapse.collapseItem id=(taxonomy.id)
                      - taxonomy.list_children&.each do |child|
                        li
                          - if child.leaf?
                            = link_to potepan_category_path(child.id, sort_order: @selected_sort_value) do
                              = child.name
                              span
                                = " (#{child.products.size})"
                          - else
                            = link_to "javascript:;", data: {toggle: "collapse", target: "##{child.id}"}, class: "side-nav-child" do
                              i.fa.fa-caret-right[aria-hidden="true"]
                              = child.name
                              span
                                = " (#{child.children.map(&:products).flatten.size})"
                            ul.collapse.collapseItem id=(child.id)
                              - child.children.each do |grandchild|
                                li
                                  = link_to potepan_category_path(grandchild.id, sort_order: @selected_sort_value) do
                                    = grandchild.name
                                    span
                                      = " (#{grandchild.products.size})"
        .panel.panel-default.filterNormal.panelColor
          .panel-heading
            | 色から探す
          .panel-body
            ul.list-unstyled
              - @colors.each do |color|
                li
                  - if @taxon.present?
                    = link_to potepan_category_path(params[:id], sort_order: @selected_sort_value, color_name: color.name) do
                      = color.presentation
                      span
                        = " (#{color.counts_products_in_current_taxon(@ids_of_products_in_current_taxon)})"
                  - elsif @search_word.present?
                    = link_to potepan_categories_path(sort_order: @selected_sort_value, color_name: color.name, search_word: @search_word) do
                      = color.presentation
                      span
                        = " (#{color.counts_products_in_current_taxon(@ids_of_products_in_current_taxon)})"
                  - else
                    = link_to potepan_categories_path(sort_order: @selected_sort_value, color_name: color.name) do
                      = color.presentation
                      span
                        = " (#{color.counts_products_in_current_taxon(@ids_of_products_in_current_taxon)})"
        .panel.panel-default.filterNormal.panelSize
          .panel-heading
            | サイズから探す
          .panel-body
            ul.list-unstyled
              - @sizes.each do |size|
                li
                  - if @taxon.present?
                    = link_to potepan_category_path(params[:id], sort_order: @selected_sort_value, size_name: size.name) do
                      = size.presentation
                      span
                        = " (#{size.counts_products_in_current_taxon(@ids_of_products_in_current_taxon)})"
                  - elsif @search_word.present?
                    = link_to potepan_categories_path(sort_order: @selected_sort_value, size_name: size.name, search_word: @search_word) do
                      = size.presentation
                      span
                        = " (#{size.counts_products_in_current_taxon(@ids_of_products_in_current_taxon)})"
                  - else
                    = link_to potepan_categories_path(sort_order: @selected_sort_value, size_name: size.name) do
                      = size.presentation
                      span
                        = " (#{size.counts_products_in_current_taxon(@ids_of_products_in_current_taxon)})"
      .col-md-9.col-sm-8.col-xs-12
        .row.filterArea
          .col-xs-6
            = form_tag(request.path, method: :get, enforce_utf8: false) do
              = hidden_field_tag :search_word, @search_word if @search_word
              = hidden_field_tag :color_name, params[:color_name] if params[:color_name]
              = hidden_field_tag :size_name, params[:size_name] if params[:size_name]
              = select_tag "sort_order", options_for_select(@sort_values, selected: @selected_sort_value), class: 'select-drop', onchange: "this.form.submit()"
          = render 'display_buttons'
          - if session[:display_style] == 'list'
            .row.productListSingle
              = render partial: 'product', collection: @products
          - else
            .row
              = render partial: 'product', collection: @products
          .mb-3
            = paginate @products
            /= page_entries_info @products
= render 'layouts/partners_logo'