config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'products#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    get :privacy_policy,            to: 'sample#privacy_policy'
    get 'categories/grid', to: 'categories#grid'
    get 'categories/list', to: 'categories#list'
    resources :products, only: [:show, :index]
    resources :categories, only: [:show, :index]
    resources :orders, only: [:index, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.slim
- flash.each do |message_type, message|
  = content_tag(:div, message, class: "alert alert-#{message_type}")

app/views/layouts/_footer.html.slim
#footer.copyRight.clearfix
  .container
    .row
      .col-sm-7.col-xs-12
        p
          | © 2016-
          = Time.current.year
          |  Copyright Potepan Store .
      .col-sm-5.col-xs-12
        ul.list-inline
          li
            a[href="https://bitbucket.org/7kamaru/potepanec/src/master/" target="_blank"]
              i.fab.fa-bitbucket
          li
            a[href="https://twitter.com/Nakamar84486715" target="_blank"]
              i.fab.fa-twitter

app/views/layouts/_header.html.slim
.header.clearfix
  .topBar
    .container
      .row
        .col-md-6.hidden-sm.hidden-xs
          ul.list-inline
            li
              a[href="https://bitbucket.org/7kamaru/potepanec/src/master/" target="_blank"]
                i.fab.fa-bitbucket
            li
              a[href="https://twitter.com/Nakamar84486715" target="_blank"]
                i.fab.fa-twitter
        .col-md-6.col-xs-12
          ul.list-inline.pull-right
            li.login-or-create-account
            li.dropdown.searchBox
              a.dropdown-toggle[href="javascript:void(0)" data-toggle="dropdown"]
                i.fa.fa-search
              ul.dropdown-menu.dropdown-menu-right
                li.search-area
                  = form_tag potepan_categories_path, id: 'form01', method: :get, enforce_utf8: false, class: 'search-box' do
                    = hidden_field_tag :sort_order, params[:sort_order] if params[:sort_order]
                    = text_field_tag :search_word, '', class: 'search-form', placeholder: 'Search products...', aria_describedy: 'basic-addon2'
                    = submit_tag '検索', class: 'input-group-addon search-button slowly-transparent', id: "basic-addon2"
            li.dropdown.dropdownCart
              - if @line_items.present?
                a.dropdown-toggle[href="javascript:void(0)" data-toggle="dropdown disabled"]
                  i.fa.fa-shopping-cart
                  span.cart-heading-1
                    = @order.item_count
                  span.cart-heading-2
                    = "#{@order_price_total}円"
                ul.dropdown-menu.dropdown-menu-right
                  li.title-line-items
                    | #{@item_or_items} in your cart
                  li
                    ul.dropdown-line-items
                      - @line_items.each do |line_item|
                        li.dropdown-line-item id="dropdown-line-item-#{line_item.id}"
                          .media-line-item
                            .media-box
                              = link_to image_tag(line_item.variant.display_image.attachment(:small), class: "media-image slowly-transparent", alt: "cart-Image"), potepan_product_path(id: line_item.variant.product.id)
                              span.media-span-delete
                                = link_to "×", potepan_order_path(id: line_item.id), method: :delete, remote: true, data: { confirm: "「#{line_item.variant.product.name}」 を削除します。よろしいですか？" }, class: "media-link-delete"
                              .line-item-quantity-dropdown
                                span.quantity-plus-dropdown
                                  = link_to potepan_order_path(order: { line_items_attributes: [id: line_item.id] }, number: @order.number, id: @order.id, calculation: 'plus'), method: :put, remote: true do
                                    span.quantity-plus-child-dropdown
                                      | +
                                span.quantity-display-dropdown
                                  span.quantity-display-child-dropdown id="quantity-dropdown-#{line_item.id}"
                                    = line_item.quantity
                                span.quantity-minus-dropdown id="quantity-minus-dropdown-#{line_item.id}"
                                  - if line_item.quantity == 1
                                    = link_to potepan_order_path(id: line_item.id), method: :delete, remote: true, data: { confirm: "「#{line_item.variant.product.name}」 を削除します。よろしいですか？" } do
                                      span.quantity-minus-child-dropdown
                                        | -
                                  - else
                                    = link_to potepan_order_path(order: { line_items_attributes: [id: line_item.id], }, number: @order.number, id: @order.id, calculation: 'minus'), method: :put, remote: true do
                                      span.quantity-minus-child-dropdown
                                        | -
                            .media-body-line-item
                              h5.media-heading
                                = link_to line_item.name, potepan_product_path(id: line_item.variant.product.id)
                                br
                                span.media-heading-price
                                  = line_item.display_price
                  li
                    .btn-group[role="group" aria-label="..."]
                      button.btn.btn-default[type="button" onclick="location.href='#{potepan_orders_path}'"]
                        | Shopping Cart
                      button.btn.btn-default[type="button"]
                        | Checkout
              - else
                = render 'layouts/no_dropdown_cart_icon'
  nav.navbar.navbar-main.navbar-default[role="navigation"]
    .container
      .navbar-header
        button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-ex1-collapse"]
          span.sr-only
            | Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to image_tag("img/logo.png", :alt => ""), potepan_path, class: "navbar-brand"
      .collapse.navbar-collapse.navbar-ex1-collapse
        ul.nav.navbar-nav.navbar-right
          li
            = link_to 'Home', potepan_path
          li.dropdown.megaDropMenu
            = link_to 'Shop', potepan_categories_path(sort_order: @selected_sort_value || nil)

app/views/layouts/_light_section.html.slim
section.lightSection.clearfix.pageHeader
  .container
    .row
      - if product.present?
        .col-xs-6
          .page-title
            h2
              = yield(:title)
        .col-xs-6
          ol.breadcrumb.pull-right
            li
              = link_to 'HOME', potepan_path
            li
              = link_to 'SHOP', potepan_categories_path
            li
              = link_to taxon[1], potepan_category_path(taxon[0])
            li.active
              | 
      - elsif taxon.present?
        .col-xs-6
          .page-title
            h2
              = link_to yield(:title), potepan_category_path(taxon: taxon.id, sort_order: sort_order)
        .col-xs-6
          ol.breadcrumb.pull-right
            li
              = link_to 'HOME', potepan_path
            li
              = link_to 'SHOP', potepan_categories_path(sort_order: sort_order)
            li.active
              | 
      - elsif default_search_word.present?
        .col-xs-6
          .page-title
            h2
              = link_to default_search_word, potepan_categories_path(search_word: search_word, sort_order: sort_order)
        .col-xs-6
          ol.breadcrumb.pull-right
            li
              = link_to 'HOME', potepan_path
            li
              = link_to 'SHOP', potepan_categories_path(sort_order: sort_order)
            li.active
              | 
      - elsif search_word.present?
        .col-xs-6
          .page-title
            h2
              = link_to "\"#{search_word}\"", potepan_categories_path(search_word: search_word, sort_order: sort_order)
        .col-xs-6
          ol.breadcrumb.pull-right
            li
              = link_to 'HOME', potepan_path
            li
              = link_to 'SHOP', potepan_categories_path(sort_order: sort_order)
            li.active
              | 
      - else
        .col-xs-6
          .page-title
            h2
              = link_to yield(:title), potepan_categories_path(sort_order: sort_order)
        .col-xs-6
          ol.breadcrumb.pull-right
            li
              = link_to 'HOME', potepan_path
            li.active
              | 

app/views/layouts/_login_modal.html.slim
#login.modal.fade.login-modal[tabindex="-1" role="dialog"]
  .modal-dialog
    .modal-content
      .modal-header
        button.close[type="button" data-dismiss="modal" aria-hidden="true"]
          | ×
        h3.modal-title
          | log in
      .modal-body
        form[action="#" method="POST" role="form"]
          .form-group
            label[for="login-email"]
              | Enter Email
            input#login-email.form-control[type="email"]
          .form-group
            label[for="login-password"]
              | Password
            input#login-password.form-control[type="password"]
          .checkbox
            label
              input[type="checkbox"]
              |  Remember Me
          button.btn.btn-primary.btn-block[type="submit"]
            | log in
          button.btn.btn-link.btn-block[type="button"]
            | Forgot Password?

app/views/layouts/_no_dropdown_cart_icon.html.slim
a.dropdown-toggle[href="#{potepan_orders_path}" data-toggle="dropdown disabled"]
  i.fa.fa-shopping-cart

app/views/layouts/_partners_logo.html.slim
section.lightSection.clearfix
  .container
    .row
      .col-xs-12
        .owl-carousel.partnersLogoSlider
          .slide
            .partnersLogo.clearfix
              = image_tag("img/home/partners/partner-01.png", :alt => "partner-img")
          .slide
            .partnersLogo.clearfix
              = image_tag("img/home/partners/partner-02.png", :alt => "partner-img")
          .slide
            .partnersLogo.clearfix
              = image_tag("img/home/partners/partner-03.png", :alt => "partner-img")
          .slide
            .partnersLogo.clearfix
              = image_tag("img/home/partners/partner-04.png", :alt => "partner-img")
          .slide
            .partnersLogo.clearfix
              = image_tag("img/home/partners/partner-05.png", :alt => "partner-img")
          .slide
            .partnersLogo.clearfix
              = image_tag("img/home/partners/partner-01.png", :alt => "partner-img")
          .slide
            .partnersLogo.clearfix
              = image_tag("img/home/partners/partner-02.png", :alt => "partner-img")
          .slide
            .partnersLogo.clearfix
              = image_tag("img/home/partners/partner-03.png", :alt => "partner-img")

app/views/layouts/_quick_view_modal.html.slim
.modal.fade.quick-view[tabindex="-1" role="dialog"]
  .modal-dialog
    .modal-content
      .modal-body
        button.close[type="button" data-dismiss="modal" aria-hidden="true"]
          | ×
        .media
          .media-left
            = image_tag("products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image")
          .media-body
            h2
              | Old Skool Navy
            h3
              | 149円
            p
              | Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.
            span.quick-drop
              select#guiest_id3.select-drop[name="guiest_id3"]
                option[value="0"]
                  | S
                option[value="1"]
                  | M
                option[value="2"]
                  | L
                option[value="3"]
                  | XL
            span.quick-drop.resizeWidth
              select#guiest_id4.select-drop[name="guiest_id4"]
                option[value="1"]
                  | 1
                option[value="2"]
                  | 2
                option[value="3"]
                  | 3
            .btn-area
              a.btn.btn-primary.btn-block[href="cart_page.html"]
                | カートへ入れる 

app/views/layouts/_rails_default.html.slim
meta[charset="utf-8"]
meta[http-equiv="X-UA-Compatible" content="IE=edge"]
meta[name="viewport" content="width=device-width, initial-scale=1"]
link[href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet"]
= csrf_meta_tags
= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', media: 'all'
= javascript_include_tag 'application'

app/views/layouts/_signup_modal.html.slim
#signup.modal.fade[tabindex="-1" role="dialog"]
  .modal-dialog
    .modal-content
      .modal-header
        button.close[type="button" data-dismiss="modal" aria-hidden="true"]
          | ×
        h3.modal-title
          | Create an account
      .modal-body
        form[action="" method="POST" role="form"]
          .form-group
            label[for="signup-email"]
              | Enter Email
            input#signup-email.form-control[type="email"]
          .form-group
            label[for="signup-password"]
              | Password
            input#signup-password.form-control[type="password"]
          .form-group
            label[for="signup-password-confirmation"]
              | Confirm Password
            input#signup-password-confirmation.form-control[type="password"]
          button.btn.btn-primary.btn-block[type="submit"]
            | Sign up

app/views/layouts/application.html.slim
doctype html
html
  head
    = render 'layouts/rails_default'
    title = full_title(page_title: yield(:title))
  body
    .main-wrapper
      - if params[:sort_order].present?
        = render 'layouts/header', sort_order: params[:sort_order]
      - else
        = render 'layouts/header', sort_order: nil
      - if flash.present?
        = render 'layouts/flash_messages'
      = yield
      = render 'layouts/footer'
    = render 'layouts/login_modal'
    = render 'layouts/signup_modal'